apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://gitlab.dennis-armbruster.de/armbruster-server/argo-cd
    path: charts/root-app/
    targetRevision: HEAD
  destination:
    server: https://imperium-armbruster.ddns.net
    namespace: argo-cd
  syncPolicy:
    automated:
      selfHeal: true
