apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: armbruster-server
  namespace: argo-cd
  annotations:
    meta.helm.sh/release-namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/dennisarmbruster95/armbruster-argo-cd.git
    path: charts/armbruster-server/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  syncPolicy:
    automated:
      selfHeal: true