apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: emberstack
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://emberstack.github.io/helm-charts/
    chart: emberstack
    targetRevision: 7.1.216
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true