apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: emberstack
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/emberstack/kubernetes-reflector/tree/main/src/helm/reflector
    chart: emberstack
    targetRevision: v7.1.216
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true