apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong
  namespace: ingress
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: ingress
  source:
    repoURL: https://charts.konghq.com
    chart: kong
    targetRevision: 2.34.0
    helm:
      values: |
        image:
          repository: kong
          tag: "3.1"
        env:
          prefix: /kong_prefix/
          database: "off"
          log_level: "debug"
          stream_listen: 0.0.0.0:1883
        ingressController:
          installCRDs: true
          enabled: true
          image:
            tag: "2.8"
        proxy:
          enabled: true
          stream:
            - containerPort: 1883
              servicePort: 1883
              protocol: TCP
        admin:
          useTLS: false
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true