apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme-http01-issuer
  namespace: ingress
spec:
  acme:
    email: dennis.armbruster@live.de
    privateKeySecretRef:
      name: issuer-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: kong
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acme-http01
  namespace: default
spec:
  secretName: cluster-acme-certificate
  dnsNames:
    - imperium-armbruster.ddns.net
  issuerRef:
    name: acme-http01-issuer
    kind: ClusterIssuer
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
