kind: KongClusterPlugin
apiVersion: configuration.konghq.com/v1
metadata:
  name: global-correlation-id
  annotaitions:
    kubernetes.io/ingress.class: kong
    labels:
      global: "true"
config:
  header_name: Kong-Request-ID
  generator: uuid#counter
  echo_downstream: false
plugin: correlation-id
---
kind: KongPlugin
apiVersion: configuration.konghq.com/v1
metadata:
  name: cors-plugin
config:
  preflight_continue: false
  credentials: true
plugin: cors