# Basic values.yaml configuration for Kong for Kubernetes (with the ingress controller)

image:
  repository: kong
  tag: "3.4.x"

env:
  prefix: /kong_prefix/
  database: "off"
  log_level: "debug"
  stream_listen: 0.0.0.0:1883

ingressController:
  installCRDs: true
  enabled: true
  image:
    tag: "3.0.x"

proxy:
  enabled: true
  stream:
    - containerPort: 1883
      servicePort: 1883
      protocol: TCP